# **tugas 2** DISKRITASI

In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
dataset= 'https://raw.githubusercontent.com/Feb11F/dataset/main/Iris.csv'
f = pd.read_csv(dataset)

In [ ]:
f.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer

In [ ]:
sepalLength = f.SepalLengthCm
sepalWidth = f.SepalWidthCm
petalLength = f.PetalLengthCm
petalWidth = f.PetalWidthCm
spesies = f.Species

In [ ]:
aa = sepalLength.values.reshape(-1,1)
ab = sepalWidth.values.reshape(-1,1)
ac = petalLength.values.reshape(-1,1)
ad = petalWidth.values.reshape(-1,1)
sp = spesies.values.reshape(-1,1)

In [ ]:
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [ ]:
est.fit(aa)
est.fit(ab)
est.fit(ac)
est.fit(ad)

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [ ]:
KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [ ]:
KBinsDiscretizer(...)

KBinsDiscretizer(n_bins=Ellipsis)

In [ ]:
KBinsDiscretizer(n_bins=Ellipsis)

KBinsDiscretizer(n_bins=Ellipsis)

In [ ]:
xa = est.transform(aa)
xb = est.transform(ab)
xc = est.transform(ac)
xd = est.transform(ad)

In [ ]:
da1 = {'SepalLengthCm':xa}
da2 = {'SepalLengthCm':xb}
da3 = {'SepalLengthCm':xc}
da4 = {'SepalLengthCm':xd}

In [ ]:
fa = pd.DataFrame(xa,columns=['SepalLengthCm'])
fb = pd.DataFrame(xb,columns=['SepalWidthCm'])
fc = pd.DataFrame(xc,columns=['SepalLengthCm'])
fd = pd.DataFrame(xd,columns=['TepalWidthCm'])
spe = pd.DataFrame(sp,columns=['Species'])

In [ ]:
datalist = [fa, fb, fc, fd, spe]
pd.concat(datalist, axis=1)

     SepalLengthCm  SepalWidthCm  SepalLengthCm  TepalWidthCm         Species
0              3.0           3.0            2.0           0.0     Iris-setosa
1              3.0           3.0            2.0           0.0     Iris-setosa
2              3.0           3.0            2.0           0.0     Iris-setosa
3              3.0           3.0            2.0           0.0     Iris-setosa
4              3.0           3.0            2.0           0.0     Iris-setosa
..             ...           ...            ...           ...             ...
145            3.0           3.0            3.0           3.0  Iris-virginica
146            3.0           3.0            3.0           3.0  Iris-virginica
147            3.0           3.0            3.0           3.0  Iris-virginica
148            3.0           3.0            3.0           3.0  Iris-virginica
149            3.0           3.0            3.0           2.0  Iris-virginica

[150 rows x 5 columns]